### ISSUE TITLE
Add a configuration location in $HOME

### ISSUE THREAD

**Issue by ndarilek** [chrys87/fenrir#47] opened 2018-11-01 15:12 UTC
It'd be nice if settings.conf could be located somewhere in $HOME but outside the source directory. I install most non-packaged software into my home directory so a restore gets me back to a comfortable system configuration. As things stand, it looks like I either have to run Fenrir from source, or keep my personal configuration in /etc.

Might be nice if ~/.config/fenrir/settings.conf could also be checked. Then maybe ~/.config/fenrir could be used for other things like user scripts.

Thanks!

**Comment by chrys87** [comment] 2018-11-02 09:16
Howdy,
Thanks for reporting.
I already started some work here some days ago.
for the Backgrounddaemon (what reads TTY1 - TTYX) it makes sense to place the config in /etc.
for the PTY emulation, to use fenrir in terminal emulators like gnome-terminal or xterm, it makes a lot of sense to take a look at ~/.config/fenrir/settings.conf
still a lot of work needs to be done here:
- fenrir should create the settings files when they are not available in home (maybe in /etc too)
- we need to take a look at this place in settings-manager.

until this happens you can start fenrir with "-s ~/path/to/your/config/settings.conf>"
to give the config to use as parameter

**Comment by chrys87** [comment] 2018-11-05 13:00
Dupe of #41

**Closed by chrys87** 2018-11-05 13:00 UTC
